#!/bin/bash
includes=`dirname $0`

source $includes/modules.library
source $includes/tools.library
source $includes/web.module
source $includes/mysql.module

module wordpress
prereq php5-gd

config working_directory /tmp
config latest_url        http://wordpress.org/latest.tar.gz
config latest_file       latest.tar.gz
config target_directory  ${web_root}/wordpress

config database          prompt
config user              prompt
config pass              prompt

function prepare {
    pushd $wordpress_working_directory
    rm -rf latest.tar.gz
    rm -rf wordpress
}

function install {
    download $wordpress_latest_url  $wordpress_latest_file
    tar -xzf $wordpress_latest_file

    echo "
<?php
define('DB_NAME', '${wordpress_database}');
define('DB_USER', '${wordpress_user}');
define('DB_PASSWORD', '${wordpress_pass}');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

define('AUTH_KEY',         'put your unique phrase here');
define('SECURE_AUTH_KEY',  'put your unique phrase here');
define('LOGGED_IN_KEY',    'put your unique phrase here');
define('NONCE_KEY',        'put your unique phrase here');
define('AUTH_SALT',        'put your unique phrase here');
define('SECURE_AUTH_SALT', 'put your unique phrase here');
define('LOGGED_IN_SALT',   'put your unique phrase here');
define('NONCE_SALT',       'put your unique phrase here');

\$table_prefix  = 'wp_';
define('WPLANG', '');
define('WP_DEBUG', false);

if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

require_once(ABSPATH . 'wp-settings.php');
" > wordpress/wp-config.php

    rsync -aqP wordpress/ $web_root/html/

    mysql.call "
        create database
            if not exists
            $wordpress_database;

        grant all
            on $wordpress_database.*
            to $wordpress_user@localhost
            identified by '$wordpress_pass';

        flush privileges;
    "
}

function cleanup {
    rm -rf latest.tar.gz
    rm -rf wordpress
    popd
}

method prepare
method install
method cleanup
