#!/bin/bash
includes=`dirname $0`

source $includes/modules.library
source $includes/tools.library
source $includes/web.module
source $includes/mysql.module

module wordpress

config working_directory /tmp
config latest_url        http://wordpress.org/latest.tar.gz
config latest_file       latest.tar.gz
config target_directory  ${web_root}/wordpress

config database          prompt
config user              prompt
config pass              prompt

function prepare {
    pushd $wordpress_working_directory
    rm -rf latest.tar.gz
    rm -rf wordpress
}

function install {
    download $wordpress_latest_url  $wordpress_latest_file
    tar -xzf $wordpress_latest_file

    mysql_call '
        create database
            if not exists
            $wordpress_database;

        grant all
            on $wordpress_database.*
            to $wordpress_user@localhost
            identified by "$wordpress_pass";

        flush privileges;
    '

    # do something with the resulting wordpress folder.
}

function cleanup {
    rm -rf latest.tar.gz
    rm -rf wordpress
    popd
}

method prepare
method install
method cleanup
